# Generated by Django 5.1.1 on 2024-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                ("orderid", models.IntegerField(primary_key=True, serialize=False)),
                ("customerid", models.IntegerField()),
                ("shipto_address", models.CharField(max_length=100)),
                ("shipto_city", models.CharField(max_length=100)),
                ("shipto_country", models.CharField(max_length=100)),
                ("shipto_postal_code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("orderitemid", models.IntegerField(primary_key=True, serialize=False)),
                ("orderid", models.IntegerField()),
                ("productid", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
